name: 'Setup node and Install dependecies'
description: 'Setup node Node.js, cache dependecies, and install them'

inputs:
  node-version:
    description: "Node.js Version"
    required: false
    default: "22"

runs:
  using: composite
  steps:
    - name: Setup Node JS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache Dependencies
      uses: actions/cache@v4
      id : cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} 
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit!='true'
      run : npm install
      shell: bash 