name: Deploy React to GitHub Pages

on:
    push:
        branches:
            - main
            - 'features/**'
        paths-ignore:
            - README.md
            - '.github/workflows/*'
            - '.github/actions/*'
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning the repo
              uses : actions/checkout@v4
            - name: Setup Node and Install Dependencies
              uses: ./.github/actions/setupnode
              with:
                node-version: 20
            - name: Run test cases
              run : npm run test
    
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Cloning the repo
              uses : actions/checkout@v4
            - name: Setup Node and Install Dependencies
              uses: ./.github/actions/setupnode
            - name: Build Project
              run : npm run build 
            - name: Upload dist artifact
              uses: actions/upload-pages-artifact@v3 
              with:
                name: github-pages
                path: dist
        

    deploy:
        needs: build
        runs-on: ubuntu-latest

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4 
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

 