name: Deploy dist folder
# on : [push, workflow_dispatch]
on:
    # push:
    #     branches:
    #         - main
    #         - 'features/**'
    #     paths-ignore:
    #         - README.md
    #         - '.github/workflows/*'
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning the repo
              uses : actions/checkout@v4
            - name: Setup Node and Install Dependencies
              uses: ./.github/actions/setupnode
              with:
                node-version: 20
            - name: Run test cases
              run : npm run test
    
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Cloning the repo
              uses : actions/checkout@v4
            - name: Setup Node and Install Dependencies
              uses: ./.github/actions/setupnode
            - name: Build Project
              run : npm run build 
            - name: Upload dist artifact
              uses: actions/upload-artifact@v4
              with:
                name: dist-files    # Where to upload the artifacts
                path: dist          # dist folder will be uploaded to `dist-files`
    
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download dist artifact
              uses: actions/download-artifact@v4
              with: 
                name: dist-files
                path: dist
            - name: Deploy dist
              run: |
                ls dist
                echo "Doploying..." 